#!/usr/bin/env python3
"""
Country detector based on aip_countries_full.json
Maps ICAO airport code prefixes to country names with flags
"""

import json
import logging
from pathlib import Path
from typing import Optional, Dict

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ICAO airport code prefixes mapped to country names
# Generated from aip_countries_full.json
ICAO_PREFIXES = {
    'OA': 'Afghanistan',
    'LA': 'Albania',
    'DA': 'Algeria',
    'LE': 'Andorra',
    'FN': 'Angola',
    'TAPA': 'Antigua and Barbuda',
    'SA': 'Argentina',
    'UD': 'Armenia',
    'Y': 'Australia',
    'LO': 'Austria',
    'UB': 'Azerbaijan',
    'MY': 'Bahamas',
    'OB': 'Bahrain',
    'VG': 'Bangladesh',
    'TBPB': 'Barbados',
    'UM': 'Belarus',
    'EB': 'Belgium',
    'MZ': 'Belize',
    'DB': 'Benin',
    'VQ': 'Bhutan',
    'SL': 'Bolivia',
    'LQ': 'Bosnia and Herzegovina',
    'SB': 'Brazil',
    'WBA': 'Brunei',
    'LZ': 'Bulgaria',
    'DF': 'Burkina Faso',
    'GV': 'Cabo Verde',
    'VDP': 'Cambodia',
    'FK': 'Cameroon',
    'C': 'Canada',
    'FE': 'Central African Republic',
    'FT': 'Chad',
    'SC': 'Chile',
    'ZB': 'China',
    'SK': 'Colombia',
    'FM': 'Comoros',
    'FC': 'Congo',
    'MR': 'Costa Rica',
    'LD': 'Croatia',
    'MU': 'Cuba',
    'LC': 'Cyprus',
    'LK': 'Czech Republic',
    'EK': 'Denmark',
    'HD': 'Djibouti',
    'TD': 'Dominica',
    'MD': 'Dominican Republic',
    'WP': 'East Timor (Timor-Leste)',
    'SE': 'Ecuador',
    'HE': 'Egypt',
    'MS': 'El Salvador',
    'FG': 'Equatorial Guinea',
    'HH': 'Eritrea',
    'EE': 'Estonia',
    'FD': 'Eswatini',
    'HA': 'Ethiopia',
    'NF': 'Fiji',
    'EF': 'Finland',
    'LF': 'France',
    'FO': 'Gabon',
    'GB': 'Gambia',
    'UG': 'Georgia',
    'ED': 'Germany',
    'DG': 'Ghana',
    'LG': 'Greece',
    'TGPY': 'Grenada',
    'MG': 'Guatemala',
    'GU': 'Guinea',
    'GG': 'Guinea-Bissau',
    'SY': 'Guyana',
    'MT': 'Haiti',
    'MH': 'Honduras',
    'VH': 'Hong Kong',
    'LH': 'Hungary',
    'BI': 'Iceland',
    'VI': 'India',
    'WI': 'Indonesia',
    'OII': 'Iran',
    'OR': 'Iraq',
    'EI': 'Ireland',
    'LL': 'Israel',
    'LI': 'Italy',
    'MK': 'Jamaica',
    'RJ': 'Japan',
    'OJ': 'Jordan',
    'UA': 'Kazakhstan',
    'HK': 'Kenya',
    'NG': 'Kiribati',
    'BK': 'Kosovo',
    'OK': 'Kuwait',
    'UO': 'Kyrgyzstan',
    'VL': 'Laos',
    'EV': 'Latvia',
    'OL': 'Lebanon',
    'FX': 'Lesotho',
    'GL': 'Liberia',
    'HL': 'Libya',
    'LS': 'Liechtenstein',
    'EY': 'Lithuania',
    'EL': 'Luxembourg',
    'VM': 'Macau',
    'FM': 'Madagascar',
    'FW': 'Malawi',
    'WM': 'Malaysia',
    'VR': 'Maldives',
    'GA': 'Mali',
    'LM': 'Malta',
    'PK': 'Marshall Islands',
    'GQ': 'Mauritania',
    'FI': 'Mauritius',
    'MM': 'Mexico',
    'PT': 'Micronesia',
    'LU': 'Moldova',
    'LF': 'Monaco',
    'ZM': 'Mongolia',
    'LY': 'Montenegro',
    'GM': 'Morocco',
    'FQ': 'Mozambique',
    'VY': 'Myanmar (Burma)',
    'FY': 'Namibia',
    'AN': 'Nauru',
    'VN': 'Nepal',
    'EH': 'Netherlands',
    'NZ': 'New Zealand',
    'MN': 'Nicaragua',
    'DR': 'Niger',
    'DN': 'Nigeria',
    'LW': 'North Macedonia',
    'EN': 'Norway',
    'OO': 'Oman',
    'OP': 'Pakistan',
    'PT': 'Palau',
    'MP': 'Panama',
    'AY': 'Papua New Guinea',
    'SG': 'Paraguay',
    'SP': 'Peru',
    'RP': 'Philippines',
    'EP': 'Poland',
    'LP': 'Portugal',
    'OT': 'Qatar',
    'LR': 'Romania',
    'UU': 'Russia',
    'HR': 'Rwanda',
    'TK': 'Saint Kitts and Nevis',
    'TL': 'Saint Lucia',
    'TV': 'Saint Vincent and the Grenadines',
    'NS': 'Samoa',
    'LID': 'San Marino',
    'OE': 'Saudi Arabia',
    'LY': 'Serbia',
    'FS': 'Seychelles',
    'GF': 'Sierra Leone',
    'WS': 'Singapore',
    'LZ': 'Slovakia',
    'LJ': 'Slovenia',
    'AG': 'Solomon Islands',
    'HC': 'Somalia',
    'FA': 'South Africa',
    'RK': 'South Korea',
    'HSS': 'South Sudan',
    'LE': 'Spain',
    'VC': 'Sri Lanka',
    'HS': 'Sudan',
    'SM': 'Suriname',
    'ES': 'Sweden',
    'LS': 'Switzerland',
    'OS': 'Syria',
    'FP': 'São Tomé and Príncipe',
    'RC': 'Taiwan',
    'UT': 'Tajikistan',
    'HT': 'Tanzania',
    'VT': 'Thailand',
    'DX': 'Togo',
    'NT': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'DT': 'Tunisia',
    'LT': 'Turkey',
    'UT': 'Turkmenistan',
    'NG': 'Tuvalu',
    'HU': 'Uganda',
    'UK': 'Ukraine',
    'OM': 'United Arab Emirates',
    'EG': 'United Kingdom',
    'K': 'United States of America',
    'SU': 'Uruguay',
    'UZ': 'Uzbekistan',
    'NI': 'Vanuatu',
    'LV': 'Vatican City',
    'SV': 'Venezuela',
    'VV': 'Vietnam',
    'OY': 'Yemen',
    'FL': 'Zambia',
    'FV': 'Zimbabwe',
}

# Country flag emojis
COUNTRY_FLAGS = {
    'Afghanistan': '🇦🇫',
    'Albania': '🇦🇱',
    'Algeria': '🇩🇿',
    'Andorra': '🇦🇩',
    'Angola': '🇦🇴',
    'Antigua and Barbuda': '🇦🇬',
    'Argentina': '🇦🇷',
    'Armenia': '🇦🇲',
    'Australia': '🇦🇺',
    'Austria': '🇦🇹',
    'Azerbaijan': '🇦🇿',
    'Bahamas': '🇧🇸',
    'Bahrain': '🇧🇭',
    'Bangladesh': '🇧🇩',
    'Barbados': '🇧🇧',
    'Belarus': '🇧🇾',
    'Belgium': '🇧🇪',
    'Belize': '🇧🇿',
    'Benin': '🇧🇯',
    'Bhutan': '🇧🇹',
    'Bolivia': '🇧🇴',
    'Bosnia and Herzegovina': '🇧🇦',
    'Brazil': '🇧🇷',
    'Brunei': '🇧🇳',
    'Bulgaria': '🇧🇬',
    'Burkina Faso': '🇧🇫',
    'Cabo Verde': '🇨🇻',
    'Cambodia': '🇰🇭',
    'Cameroon': '🇨🇲',
    'Canada': '🇨🇦',
    'Central African Republic': '🇨🇫',
    'Chad': '🇹🇩',
    'Chile': '🇨🇱',
    'China': '🇨🇳',
    'Colombia': '🇨🇴',
    'Comoros': '🇰🇲',
    'Congo': '🇨🇬',
    'Costa Rica': '🇨🇷',
    'Croatia': '🇭🇷',
    'Cuba': '🇨🇺',
    'Cyprus': '🇨🇾',
    'Czech Republic': '🇨🇿',
    'Denmark': '🇩🇰',
    'Djibouti': '🇩🇯',
    'Dominica': '🇩🇲',
    'Dominican Republic': '🇩🇴',
    'East Timor (Timor-Leste)': '🇹🇱',
    'Ecuador': '🇪🇨',
    'Egypt': '🇪🇬',
    'El Salvador': '🇸🇻',
    'Equatorial Guinea': '🇬🇶',
    'Eritrea': '🇪🇷',
    'Estonia': '🇪🇪',
    'Eswatini': '🇸🇿',
    'Ethiopia': '🇪🇹',
    'Fiji': '🇫🇯',
    'Finland': '🇫🇮',
    'France': '🇫🇷',
    'Gabon': '🇬🇦',
    'Gambia': '🇬🇲',
    'Georgia': '🇬🇪',
    'Germany': '🇩🇪',
    'Ghana': '🇬🇭',
    'Greece': '🇬🇷',
    'Grenada': '🇬🇩',
    'Guatemala': '🇬🇹',
    'Guinea': '🇬🇳',
    'Guinea-Bissau': '🇬🇼',
    'Guyana': '🇬🇾',
    'Haiti': '🇭🇹',
    'Honduras': '🇭🇳',
    'Hong Kong': '🇭🇰',
    'Hungary': '🇭🇺',
    'Iceland': '🇮🇸',
    'India': '🇮🇳',
    'Indonesia': '🇮🇩',
    'Iran': '🇮🇷',
    'Iraq': '🇮🇶',
    'Ireland': '🇮🇪',
    'Israel': '🇮🇱',
    'Italy': '🇮🇹',
    'Jamaica': '🇯🇲',
    'Japan': '🇯🇵',
    'Jordan': '🇯🇴',
    'Kazakhstan': '🇰🇿',
    'Kenya': '🇰🇪',
    'Kiribati': '🇰🇮',
    'Kosovo': '🇽🇰',
    'Kuwait': '🇰🇼',
    'Kyrgyzstan': '🇰🇬',
    'Laos': '🇱🇦',
    'Latvia': '🇱🇻',
    'Lebanon': '🇱🇧',
    'Lesotho': '🇱🇸',
    'Liberia': '🇱🇷',
    'Libya': '🇱🇾',
    'Liechtenstein': '🇱🇮',
    'Lithuania': '🇱🇹',
    'Luxembourg': '🇱🇺',
    'Macau': '🇲🇴',
    'Madagascar': '🇲🇬',
    'Malawi': '🇲🇼',
    'Malaysia': '🇲🇾',
    'Maldives': '🇲🇻',
    'Mali': '🇲🇱',
    'Malta': '🇲🇹',
    'Marshall Islands': '🇲🇭',
    'Mauritania': '🇲🇷',
    'Mauritius': '🇲🇺',
    'Mexico': '🇲🇽',
    'Micronesia': '🇫🇲',
    'Moldova': '🇲🇩',
    'Monaco': '🇲🇨',
    'Mongolia': '🇲🇳',
    'Montenegro': '🇲🇪',
    'Morocco': '🇲🇦',
    'Mozambique': '🇲🇿',
    'Myanmar (Burma)': '🇲🇲',
    'Namibia': '🇳🇦',
    'Nauru': '🇳🇷',
    'Nepal': '🇳🇵',
    'Netherlands': '🇳🇱',
    'New Zealand': '🇳🇿',
    'Nicaragua': '🇳🇮',
    'Niger': '🇳🇪',
    'Nigeria': '🇳🇬',
    'North Macedonia': '🇲🇰',
    'Norway': '🇳🇴',
    'Oman': '🇴🇲',
    'Pakistan': '🇵🇰',
    'Palau': '🇵🇼',
    'Panama': '🇵🇦',
    'Papua New Guinea': '🇵🇬',
    'Paraguay': '🇵🇾',
    'Peru': '🇵🇪',
    'Philippines': '🇵🇭',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Qatar': '🇶🇦',
    'Romania': '🇷🇴',
    'Russia': '🇷🇺',
    'Rwanda': '🇷🇼',
    'Saint Kitts and Nevis': '🇰🇳',
    'Saint Lucia': '🇱🇨',
    'Saint Vincent and the Grenadines': '🇻🇨',
    'Samoa': '🇼🇸',
    'San Marino': '🇸🇲',
    'Saudi Arabia': '🇸🇦',
    'Serbia': '🇷🇸',
    'Seychelles': '🇸🇨',
    'Sierra Leone': '🇸🇱',
    'Singapore': '🇸🇬',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Solomon Islands': '🇸🇧',
    'Somalia': '🇸🇴',
    'South Africa': '🇿🇦',
    'South Korea': '🇰🇷',
    'South Sudan': '🇸🇸',
    'Spain': '🇪🇸',
    'Sri Lanka': '🇱🇰',
    'Sudan': '🇸🇩',
    'Suriname': '🇸🇷',
    'Sweden': '🇸🇪',
    'Switzerland': '🇨🇭',
    'Syria': '🇸🇾',
    'São Tomé and Príncipe': '🇸🇹',
    'Taiwan': '🇹🇼',
    'Tajikistan': '🇹🇯',
    'Tanzania': '🇹🇿',
    'Thailand': '🇹🇭',
    'Togo': '🇹🇬',
    'Tonga': '🇹🇴',
    'Trinidad and Tobago': '🇹🇹',
    'Tunisia': '🇹🇳',
    'Turkey': '🇹🇷',
    'Turkmenistan': '🇹🇲',
    'Tuvalu': '🇹🇻',
    'Uganda': '🇺🇬',
    'Ukraine': '🇺🇦',
    'United Arab Emirates': '🇦🇪',
    'United Kingdom': '🇬🇧',
    'United States of America': '🇺🇸',
    'Uruguay': '🇺🇾',
    'Uzbekistan': '🇺🇿',
    'Vanuatu': '🇻🇺',
    'Vatican City': '🇻🇦',
    'Venezuela': '🇻🇪',
    'Vietnam': '🇻🇳',
    'Yemen': '🇾🇪',
    'Zambia': '🇿🇲',
    'Zimbabwe': '🇿🇼',
}

# Load countries from JSON file
_countries_data = None

def load_countries_data():
    """Load countries data from JSON file"""
    global _countries_data
    if _countries_data is None:
        json_path = Path(__file__).parent / 'assets' / 'aip_countries_full.json'
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                _countries_data = json.load(f)
            logger.info(f"Loaded {len(_countries_data)} countries from JSON file")
        except Exception as e:
            logger.error(f"Failed to load countries JSON: {e}")
            _countries_data = []
    return _countries_data

def get_country_from_code(airport_code: str) -> Optional[Dict[str, str]]:
    """
    Detect country from airport code using ICAO prefixes
    
    Args:
        airport_code: Airport code (e.g., KJFK, LFBA, EETN, EVRA)
        
    Returns:
        Dictionary with country info or None if not found
        Format: {'country': 'Country Name', 'region': 'REGION', 'code': 'PREFIX', 'flag': '🇺🇸'}
    """
    airport_code = airport_code.upper().strip()
    
    if not airport_code or len(airport_code) < 3:
        return None
    
    # Check prefixes in order: 3-letter, 2-letter, 1-letter (longer matches take precedence)
    for prefix_len in [3, 2, 1]:
        if len(airport_code) >= prefix_len:
            prefix = airport_code[:prefix_len]
            if prefix in ICAO_PREFIXES:
                country_name = ICAO_PREFIXES[prefix]
                
                # Try to find this country in the JSON file for more details
                countries_data = load_countries_data()
                flag_emoji = COUNTRY_FLAGS.get(country_name, '🏳️')
                
                # If flag not found, try case-insensitive match
                if flag_emoji == '🏳️':
                    for key, value in COUNTRY_FLAGS.items():
                        if key.upper() == country_name.upper():
                            flag_emoji = value
                            break
                
                for country_data in countries_data:
                    if country_data.get('country', '').strip() == country_name:
                        return {
                            'country': country_data.get('country', country_name),
                            'region': country_data.get('region', 'UNKNOWN'),
                            'code': prefix,
                            'type': country_data.get('type', 'Unknown'),
                            'link': country_data.get('link', ''),
                            'flag': flag_emoji
                        }
                
                # If not found in JSON, return basic info with flag
                return {
                    'country': country_name,
                    'region': 'UNKNOWN',
                    'code': prefix,
                    'flag': flag_emoji
                }
    
    return None

def get_country_name(airport_code: str) -> Optional[str]:
    """Get just the country name for an airport code"""
    country_info = get_country_from_code(airport_code)
    return country_info.get('country') if country_info else None
