# Railway will auto-detect Dockerfile and use it
# No railway.toml builder configuration needed

[deploy]
startCommand = "python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "0"

